version: 1

services:
  - type: web
    name: neurologist
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: |
      gunicorn stroke_response.wsgi:application -c gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DEBUG
        value: False
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: true
    staticPublishPath: ./staticfiles
