# Generated by Django 5.2 on 2025-05-01 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technician', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('diagnosis', models.CharField(blank=True, choices=[('ISCHEMIC', 'Ischemic Stroke'), ('HEMORRHAGIC', 'Hemorrhagic Stroke'), ('TIA', 'Transient Ischemic Attack'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('diagnosis_notes', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True, help_text='List prescribed medications and dosages')),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('neurologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='technician.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
