# Generated by Django 4.2.20 on 2025-05-02 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neurologist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('TPA', 'Tissue Plasminogen Activator (tPA)'), ('ANTICOAGULANT', 'Anticoagulant Therapy'), ('ANTIPLATELET', 'Antiplatelet Therapy'), ('ANTIHYPERTENSIVE', 'Antihypertensive Medication'), ('OTHER', 'Other Treatment')], max_length=20)),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('administration_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='neurologist.consultation')),
            ],
        ),
    ]
