# Generated by Django 5.2 on 2025-05-01 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_pressure_diastolic',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_pressure_systolic',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='chief_complaint',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='glasgow_coma_scale',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_rate',
            field=models.IntegerField(default=45, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='oxygen_saturation',
            field=models.IntegerField(default=92, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='respiratory_rate',
            field=models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=37, max_digits=4),
            preserve_default=False,
        ),
    ]
