# Generated by Django 5.2 on 2025-05-01 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0002_patient_blood_pressure_diastolic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ct_scans/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the CT scan')),
                ('date_taken', models.DateField(help_text='Date the CT scan was taken')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_scans', to='technician.patient')),
            ],
            options={
                'ordering': ['-date_taken'],
            },
        ),
    ]
