# Generated by Django 5.2 on 2025-05-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0003_ctscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nihss',
            field=models.TextField(blank=True, help_text='National Institutes of Health Stroke Scale score and details'),
        ),
    ]
