# Generated by Django 4.2.20 on 2025-05-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('critical', 'Critical'), ('info', 'Info'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=20),
        ),
    ]
